x-instance-common: &instance_common
  image: zms3:debug
  build:
    context: .
    dockerfile: ./Dockerfile.debug
    args:
      - INSTANCE_DIR=${INSTANCE_DIR}
      - VENV_DIR=${VENV_DIR}
      - IS_DEBUG=true
      - UID=${UID}
      - GID=${GID}
  depends_on:
    - zeo
  user: zope
  volumes:
    - ./instance/:${INSTANCE_DIR}/:rw
    - ${SRC_MOUNT}/:${SRC_DIR}/:rw

  ### HINT: VScode-Server will be started in the container automatically
  ### and can be accessed via the browser at http://localhost:8888
  ### The VSCode-Server will be started with the workspace and
  ### Zope Instance has be started manually with VSCode-Python Debugger
  command: >
    bash -c "
      memcached -u zope -m 64 -p 11211 &
      code-server --bind-addr 0.0.0.0:8888 --disable-telemetry --disable-update-check --user-data-dir /home/zope/.local/share/code-server --auth none ${INSTANCE_DIR}/.vscode/Docker.code-workspace
    "

  networks:
    - zms_network

networks:
  zms_network:
    driver: bridge

services:
  ### Zope Instance for Debugging
  instance_debug:
    <<: *instance_common
    environment:
      - PYTHONUNBUFFERED="1"
      - SOFTWARE_HOME="${VENV_DIR}/bin"
      - PYTHON="${VENV_DIR}bin/python"
      - HTTP_PORT=8080
      - READ_ONLY=false
      - DB_HOST="host.docker.internal" # Use this to access the host's MariaDB server
      - DB_PORT="3306"
    ports:
      - "8080:8080"
      - "8888:8888" # Code-server port

  ### ZEO: Zope Enterprise Objects
  zeo:
    <<: *instance_common
    depends_on: []
    command: >
      bash -c "
      ${SRC_DIR}/.devcontainer/start_zeo.sh &
      sleep infinity
      "